### ISSUE TITLE
3D Modeling Kit limit

### ISSUE THREAD

**Issue by lvonasek** [HMS-Core/hms-3d-modeling-demo#11]
In 3D Live Scanner, users started complaining that the reconstruction does not work. I investigated into it and they keep receiving following error: `get taskID error 1118: The request has reached the max limit`

Would it be possible to extend the limit? The pro version of the app does not suffer from this issue.

**Comment by coolleizhu** [comment]
Because of the bearer capacity of the server, we limited the usage quota.
For your case, we will extend the limit and contact with you later.

**Comment by lvonasek** [comment]
Thank you @coolleizhu
