### ISSUE TITLE
Unsupported on some devices

### ISSUE THREAD

**Issue by lvonasek** [HMS-Core/hms-3d-modeling-demo#2]
Some devices (e.g. Samsung Galaxy Note 20 Ultra SM-N986B) do not work.

The issue is probably that cameratakelib opens all rear facing cameras at the same time which some devices do not support (I am waiting on user of my app to confirm this).

**Comment by lvonasek** [comment]
Confirmed by the user. Opening just one camera fixed the problem.

**Comment by caibobitHuawei** [comment]
The problem has been resolved. We will update the camera to the CameraX API to avoid similar problems.
