### ISSUE TITLE
Any solution to create model by manual uploading of images store on the phone?

### ISSUE THREAD

**Issue by yllowcool** [HMS-Core/hms-3d-modeling-demo#3]
Hi, I need help here, to test the capabilities of this HMS 3D modeling app, I have already multiple images 360deg view of the object stored in my phone, how do I manual upload the images to the app instead of using camera to take pictures?

**Comment by Mike-mei** [comment]
Create the modeling3dReconstructEngine by following the process in this demo, then [upload the image path](https://developer.huawei.com/consumer/en/doc/development/graphics-References/modeling3dreconstructengine-0000001153013003#section4042mcpsimp).

**Comment by caibobitHuawei** [comment]
We will consider adding upload methods, such as selecting images and specifying file paths, to make modeling easier.

**Comment by caibobitHuawei** [comment]
The lastest code  can choose the floder of the pictures to upload

**Comment by caibobitHuawei** [comment]
The lastest code can choose the folder of the pictures to upload
