### ISSUE TITLE
upload error: data processing location not set 

### ISSUE THREAD

**Issue by xuanwenchao** [HMS-Core/hms-3d-modeling-demo#4]
run it in my android phone after download demo "modeling3dApp" and compile with android studio.

**Comment by Mike-mei** [comment]
Please refer to this solution on [StackOverflow](https://stackoverflow.com/questions/68723347/3d-modeling-kit-crash-when-uploading-expected-url-scheme-http-or-https-bu)

**Comment by caibobitHuawei** [comment]
You can solve the issus in the following website:
https://developer.huawei.com/consumer/cn/doc/development/graphics-Guides/faq-0000001111559676
