### ISSUE TITLE
Long processing queues.

### ISSUE THREAD

**Issue by lvonasek** [HMS-Core/hms-3d-modeling-demo#9]
Since the beginning of this week many users of 3D Live Scanner report that processing queue takes longer than 30 minutes. What it be possible to allocate to service more resources?

Thank you in advance.

**Comment by Mike-mei** [comment]
1. Currently, the background of the product is an asynchronous modeling process. If multiple people are modeling at the same time during peak hours, there will be the problem of objective queuing.

2. Every day, the background calculates and evaluates the amount of modeling tasks in a day. If the number of tasks is too large to meet the needs of current users, we will consider upgrading and expanding the server in the future.

3. At present, it is still recommended for developers to consider adopting the asynchronous modeling mode shown in our demo. The optimized APP usage can better improve modeling efficiency and user experience.

**Comment by lvonasek** [comment]
Thank you @Mike-mei. The problem is that the usage are not peaks anymore, the user based of the app increased too much and I receive many mails complaining about Huawei 3D Modeling Kit every day. I am using asynchronous modeling, however I do not allow a parallel model processing due this reasons:
1) Unknown service costs in the future (I cannot afford to let the users overuse the service)
2) The service becomes slow when there are too many requests in parallel
3) It is better user experience when user does a 3D scan, receive result and see what went wrong. Instead of doing many 3D scans and in a few hours see there are all wrong.

**Comment by Mike-mei** [comment]
Expansion has been completed, please pay attention to the actual situation.

**Comment by lvonasek** [comment]
Great, thank you.
